asercoes:
  - tipo: container_rodando
    nome: lab-10-app

  - tipo: http_responde
    url: http://localhost:8097
    status: 200

  - tipo: http_corpo_contem
    url: http://localhost:8097
    texto: '"versao":"1.0"'

  - tipo: imagem_no_registry
    referencia: localhost:5000/lab-10-app:1.0
    descricao: a imagem v1.0 está publicada no registry
