asercoes:
  - tipo: container_saudavel
    nome: lab-08-db-1

  - tipo: container_saudavel
    nome: lab-08-api-1

  - tipo: container_rodando
    nome: lab-08-web-1

  - tipo: http_responde
    url: http://localhost:8095
    status: 200

  - tipo: http_corpo_contem
    url: http://localhost:8095
    texto: "O api disse: pinguim-rei"
