services:
  servidor:
    image: learning-infra-linux:1
    build: .
    container_name: learning-infra-linux
    hostname: aurora
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /var/log/aurora:size=8m,nr_inodes=2048,mode=755
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
